### ISSUE TITLE
[kim hyung eun] My practice repository

### ISSUE THREAD

**Issue by khe8402** [kccistc/intel-02#18]
* Name: Kim hyung eun

* GitHub account: khe8402

* My practice repository URL://https://github.com/khe8402/my-projectxx.git

**Comment by khe8402** [comment]
> * Name: Kim hyung eun
> * GitHub account: abcde
> * My practice repository URL://https://github.com/abcde/my-projectxx.git

**Comment by mokiya** [comment]
금일 실습, 수고하셨습니다!
