### ISSUE TITLE
[hyeanhong An] My practice repository

### ISSUE THREAD

**Issue by simpleis6est** [kccistc/intel-02#21]
* Name: hyeanhong An
* Github account: simpleis6est
* My practice repository URL: https://github.com/simpleis6est/newpj.git

**Comment by mokiya** [comment]
practice repository link에 접속이 안됩니다. 확인부탁해요~

**Comment by simpleis6est** [comment]
private 처리가되어있었습니다. 방금 public 으로 전환하였습니다.

**Comment by mokiya** [comment]
눼눼~ 수고하셨습니다! 수고하셨습니다! :-)

**Comment by simpleis6est** [comment]
넵 감사합니다!
