### ISSUE TITLE
[Yu Nayeong] My practice repository

### ISSUE THREAD

**Issue by YuNayeong** [kccistc/intel-02#24]
* Name : Yu Nayeong

* GitHub account : YuNayeong

* My practice repository URL : https://github.com/YuNayeong/Intel.git

**Comment by mokiya** [comment]
Practice link에 접속이 안됩니다. 확인부탁해요.

**Comment by YuNayeong** [comment]
수정했습니다!

**Comment by mokiya** [comment]
수고하셨습니다! :)
